apiVersion: v1
kind: Secret
metadata:
  name: keda-kafka-secrets
  namespace: keda-demo
data:
  sasl: cGxhaW50ZXh0Cg==
  tls: ZW5hYmxlCg==
  username: b3Jhc2VqYXBhbi9vcmFjbGVpZGVudGl0eWNsb3Vkc2VydmljZS90YWt1eWEubmlpdGFAb3JhY2xlLmNvbS9vY2lkMS5zdHJlYW1wb29sLm9jMS5hcC10b2t5by0xLmFtYWFhYWFhc3NsNjVpcWF4ZXBuemd5eWsyY3l2dHpzaG9ycHF0eGJucm96cGFxdXltY2EyZ2dxNXF0YQ==
  password: RkhMe1BNWURvZ0NXbzc2TXkpeCM=
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-kafka-credential
  namespace: keda-demo
spec:
  secretTargetRef:
  - parameter: sasl
    name: keda-kafka-secrets
    key: sasl
  - parameter: username
    name: keda-kafka-secrets
    key: username
  - parameter: password
    name: keda-kafka-secrets
    key: password
  - parameter: tls
    name: keda-kafka-secrets
    key: tls